apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
 strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate    
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 995153328861.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
          ports:
            - containerPort: 8080
